using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;
using Autogenerated;

namespace Autogenerated.Tests
{
    [TestFixture]
    public class Class5Test
    {
        [Test]
        public void Method1Test()
        {
            Assert.Fail("autogenerated");
        }
    }
}