using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;
using Autogenerated;
using TestClasses;

namespace Autogenerated.Tests
{
    [TestFixture]
    public class Class5Test
    {
        private Class5 Class5TestObject;
        [SetUp]
        public void SetUp()
        {
            Class5TestObject = new Class5();
        }

        [Test]
        public void Method1Test()
        {
            //Act
            Class5TestObject.Method1();
            //Assert
            Assert.Fail("autogenerated");
        }
    }
}