using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;
using Autogenerated;
using TestClasses;

namespace Autogenerated.Tests
{
    [TestFixture]
    public class Class1Test
    {
        private Class1 Class1TestObject;
        [SetUp]
        public void SetUp()
        {
            Class1TestObject = new Class1();
        }

        [Test]
        public void Method1Test()
        {
            //Arrange
            string s = default;
            //Act
            string actual = Class1TestObject.Method1(s);
            //Assert
            string expected = default;
            Assert.That(actual, Is.EqualTo(expected));
            Assert.Fail("autogenerated");
        }

        [Test]
        public void Method2Test()
        {
            //Act
            Class1TestObject.Method2();
            //Assert
            Assert.Fail("autogenerated");
        }
    }
}