using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;
using Autogenerated;
using TestClasses;

namespace Autogenerated.Tests
{
    [TestFixture]
    public class Class2Test
    {
        private Class2 Class2TestObject;
        [SetUp]
        public void SetUp()
        {
            Class2TestObject = new Class2();
        }

        [Test]
        public void Method1Test()
        {
            //Arrange
            int a = default;
            int b = default;
            //Act
            int actual = Class2TestObject.Method1(a, b);
            //Assert
            int expected = default;
            Assert.That(actual, Is.EqualTo(expected));
            Assert.Fail("autogenerated");
        }

        [Test]
        public void Method2Test()
        {
            //Act
            Class2TestObject.Method2();
            //Assert
            Assert.Fail("autogenerated");
        }
    }
}