using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NUnit.Framework;
using Moq;
using Autogenerated;
using TestClasses;

namespace Autogenerated.Tests
{
    [TestFixture]
    public class Class3Test
    {
        private Class3 Class3TestObject;
        [SetUp]
        public void SetUp()
        {
            Class3TestObject = new Class3();
        }

        [Test]
        public void Method1Test()
        {
            //Act
            Class3TestObject.Method1();
            //Assert
            Assert.Fail("autogenerated");
        }

        [Test]
        public void Method2Test()
        {
            //Act
            Class3TestObject.Method2();
            //Assert
            Assert.Fail("autogenerated");
        }
    }
}